name: Php Unit

on:
  push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  php_unit:
    runs-on: ubuntu-latest
    name: Run phpUnit test
    steps:
      - uses: actions/checkout@v3
      - uses: GuillaumeFalourd/phpunit@main
        with:
          who-to-greet: World
